---
title: "Cost-effectiveness analysis"
output: html_document
date: "`r format(Sys.time(), '%d %B, %Y')`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction

This model is based on papers by [Briggs 1998](https://pubmed.ncbi.nlm.nih.gov/10178664/)
and
[Briggs 2000](https://pubmed.ncbi.nlm.nih.gov/10977389/)

# Data

# Methods

## Model Fitting

# Results

```{r ceplane, fig.width=5, fig.cap="my plot", }
plot(10, 0.1,
     xlab = "Incremental QALYs",
     ylab = "Incremental costs",
     xlim = c(-1, 12),
     ylim = c(-0.1, 0.2),
     pch = 20)
abline(a = 0, b = 0.02)
```


intervention | cost | QALY | delta c | delta QALY | ICER
-------------|------|------|---------|------------|-----
drug a       | 100  | 0.5  |         |            |
drug b       | 50   | 0.1  |  50     |  0.4       | 20

```{r echo=FALSE}
data.frame(intervention = c("drug a", "drug b"),
           cost = c(100,50),
           QALY = c(0.5,0.1),
           delta_c = c(NA, 50),
           delta_QALY = c(NA, 0.4),
           ICER = c(NA, 20)) |> 
knitr::kable()
```

```{r}
# can define as it appears in the table
tibble::tribble(~intervention, ~cost, ~QALY, ~delta_c, ~delta_QALY, ~ICER,
                "drug a",      100,   0.5,   NA,       NA,          NA,
                "drug b",      50,    0.1,   50,       0.4,         20)
```


# Conclusions

## Recommendations
